### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by Akshay602** [bemoss/BEMOSS3.5#38]
Kindly help me to install the project, the below given error is caused due to missing server,
Creating virtual Python environment
Downloading virtualenv DOAP record
Traceback (most recent call last):
  File "bootstrap.py", line 404, in <module>
    main()
  File "bootstrap.py", line 387, in main
    options.force_version, options.verbose)
  File "bootstrap.py", line 208, in bootstrap
    builder.create(dest, verbose)
  File "bootstrap.py", line 186, in create
    self.download(tmpdir)
  File "bootstrap.py", line 171, in download
    self.get_version()
  File "bootstrap.py", line 160, in get_version
    with contextlib.closing(self._fetch(doap_url)) as response:
  File "bootstrap.py", line 147, in _fetch
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 410: DOAP is no longer supported.

**Comment by Akshay602** [comment]
This was caused due to missing link, and i was not having virtual environment setup i.e volttron was not installed. Installed manually and configured it as required comment rm statement in install.sh file. This should solved the issue.
